//! Detecting AI assistance in commit messages.

use regex::Regex;
use serde::Serialize;
use std::sync::LazyLock;

/// A model or tool credited in commit messages.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct Credit {
    pub name: String,
    /// Commits crediting it.
    pub commits: u32,
    /// Lines added / removed by those commits.
    pub added: u64,
    pub removed: u64,
}

/// AI attribution found in the commit message(s) of a PR or commit.
#[derive(Debug, Default, Clone, PartialEq, Serialize)]
pub struct Usage {
    /// From `Co-Authored-By:` trailers, e.g. `Claude Sonnet 5.5`; most commits first.
    pub models: Vec<Credit>,
    /// From `Generated with ...` lines, e.g. `Claude Code`; most commits first.
    pub tools: Vec<Credit>,
    /// Commits that credit any model or tool, and the lines they added / removed.
    pub ai_commits: u32,
    pub ai_added: u64,
    pub ai_removed: u64,
}

impl Usage {
    pub fn is_empty(&self) -> bool {
        self.models.is_empty() && self.tools.is_empty()
    }
}

static VENDOR: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(
        r"(?i)claude|anthropic|copilot|openai|chatgpt|\bgpt[-\s]?\d|codex|gemini|cursor|aider|windsurf|codeium|devin-ai|amazon q|\bllama|mistral|deepseek|\bgrok\b",
    )
    .unwrap()
});

static CO_AUTHOR: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"(?im)^\s*co-authored-by:\s*(.+?)\s*(?:<([^>]*)>)?\s*$").unwrap());

static GENERATED: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"(?im)generated\s+(?:with|by|using)\s+\[?([^\]\(\n]+)").unwrap());

/// AI attribution in a single commit message; each credit counts that one commit.
pub fn detect(message: &str) -> Usage {
    let mut usage = Usage::default();
    for c in CO_AUTHOR.captures_iter(message) {
        let name = c[1].trim();
        let email = c.get(2).map_or("", |m| m.as_str());
        if VENDOR.is_match(name) || VENDOR.is_match(email) {
            credit(&mut usage.models, name, 1, 0, 0, true);
        }
    }
    for c in GENERATED.captures_iter(message) {
        let tool = c[1].trim().trim_end_matches(['.', ')', ']', ' ']);
        if VENDOR.is_match(tool) {
            credit(&mut usage.tools, tool, 1, 0, 0, true);
        }
    }
    usage.ai_commits = !usage.is_empty() as u32;
    usage
}

/// Combines the commits of a PR, given as `(message, lines added, lines removed)`. Models and
/// tools are ordered by how many commits credit them (ties keep the order first seen).
pub fn combine<'a>(commits: impl IntoIterator<Item = (&'a str, u64, u64)>) -> Usage {
    let mut total = Usage::default();
    for (message, added, removed) in commits {
        let u = detect(message);
        if u.is_empty() {
            continue;
        }
        total.ai_commits += 1;
        total.ai_added += added;
        total.ai_removed += removed;
        for c in u.models {
            credit(&mut total.models, &c.name, 1, added, removed, false);
        }
        for c in u.tools {
            credit(&mut total.tools, &c.name, 1, added, removed, false);
        }
    }
    total.models.sort_by(|a, b| b.commits.cmp(&a.commits));
    total.tools.sort_by(|a, b| b.commits.cmp(&a.commits));
    total
}

/// Adds to the credit for `name` (case-insensitive). With `once`, a name that's already
/// listed is left alone (the same trailer repeated in one message).
fn credit(list: &mut Vec<Credit>, name: &str, commits: u32, added: u64, removed: u64, once: bool) {
    match list.iter_mut().find(|c| c.name.eq_ignore_ascii_case(name)) {
        Some(_) if once => {}
        Some(c) => {
            c.commits += commits;
            c.added += added;
            c.removed += removed;
        }
        None => list.push(Credit {
            name: name.to_string(),
            commits,
            added,
            removed,
        }),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn names(c: &[Credit]) -> Vec<&str> {
        c.iter().map(|c| c.name.as_str()).collect()
    }

    #[test]
    fn claude_code_footer() {
        let u = detect(
            "Fix thing\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\n\n\
             Co-Authored-By: Claude Sonnet 5.5 <noreply@anthropic.com>",
        );
        assert_eq!(names(&u.models), vec!["Claude Sonnet 5.5"]);
        assert_eq!(names(&u.tools), vec!["Claude Code"]);
        assert_eq!(u.ai_commits, 1);
    }

    #[test]
    fn ignores_humans_and_generators() {
        let u = detect("Co-authored-by: Jane Doe <jane@example.com>\nGenerated by protoc");
        assert!(u.is_empty());
        assert_eq!(u.ai_commits, 0);
    }

    #[test]
    fn matches_on_email_and_other_vendors() {
        let u = detect(
            "Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>\n\
             Co-authored-by: bot <x@openai.com>",
        );
        assert_eq!(names(&u.models), vec!["Copilot", "bot"]);
    }

    #[test]
    fn repeated_trailer_counts_once() {
        let u = detect(
            "Co-authored-by: Claude <a@anthropic.com>\nCo-authored-by: claude <a@anthropic.com>",
        );
        assert_eq!(u.models.len(), 1);
        assert_eq!(u.models[0].commits, 1);
    }

    #[test]
    fn combine_orders_by_commit_count_and_sums_lines() {
        let opus = "Co-authored-by: Claude Opus 5.5 <noreply@anthropic.com>";
        let sonnet = "Co-Authored-By: claude sonnet 5 <noreply@anthropic.com>";
        // tie (2 each) keeps first seen
        let u = combine([
            (opus, 1, 0),
            (sonnet, 2, 0),
            ("plain", 100, 100),
            (sonnet, 4, 1),
            (opus, 8, 0),
        ]);
        assert_eq!(names(&u.models), vec!["Claude Opus 5.5", "claude sonnet 5"]);
        let u = combine([
            (sonnet, 2, 0),
            (sonnet, 4, 1),
            (opus, 8, 3),
            ("plain", 5, 5),
        ]);
        assert_eq!(names(&u.models), vec!["claude sonnet 5", "Claude Opus 5.5"]);
        assert_eq!(
            (u.models[0].commits, u.models[0].added, u.models[0].removed),
            (2, 6, 1)
        );
        // lines and commits of the non-AI commit are excluded
        assert_eq!((u.ai_commits, u.ai_added, u.ai_removed), (3, 14, 4));
    }
}
