//! Detecting AI assistance in commit messages.

use regex::Regex;
use serde::Serialize;
use std::sync::LazyLock;

/// A model or tool credited in commit messages, with how many commits credit it.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct Credit {
    pub name: String,
    pub commits: u32,
}

/// AI attribution found in the commit message(s) of a PR or commit.
#[derive(Debug, Default, Clone, PartialEq, Serialize)]
pub struct Usage {
    /// From `Co-Authored-By:` trailers, e.g. `Claude Sonnet 5.5`; most commits first.
    pub models: Vec<Credit>,
    /// From `Generated with ...` lines, e.g. `Claude Code`; most commits first.
    pub tools: Vec<Credit>,
    /// Number of commits that credit any model or tool.
    pub ai_commits: u32,
}

impl Usage {
    pub fn is_empty(&self) -> bool {
        self.models.is_empty() && self.tools.is_empty()
    }
}

static VENDOR: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(
        r"(?i)claude|anthropic|copilot|openai|chatgpt|\bgpt[-\s]?\d|codex|gemini|cursor|aider|windsurf|codeium|devin-ai|amazon q|\bllama|mistral|deepseek|\bgrok\b",
    )
    .unwrap()
});

static CO_AUTHOR: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"(?im)^\s*co-authored-by:\s*(.+?)\s*(?:<([^>]*)>)?\s*$").unwrap());

static GENERATED: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"(?im)generated\s+(?:with|by|using)\s+\[?([^\]\(\n]+)").unwrap());

/// AI attribution in a single commit message; every credit counts one commit.
pub fn detect(message: &str) -> Usage {
    let mut usage = Usage::default();
    for c in CO_AUTHOR.captures_iter(message) {
        let name = c[1].trim();
        let email = c.get(2).map_or("", |m| m.as_str());
        if VENDOR.is_match(name) || VENDOR.is_match(email) {
            credit(&mut usage.models, name, 1);
        }
    }
    for c in GENERATED.captures_iter(message) {
        let tool = c[1].trim().trim_end_matches(['.', ')', ']', ' ']);
        if VENDOR.is_match(tool) {
            credit(&mut usage.tools, tool, 1);
        }
    }
    usage.ai_commits = !usage.is_empty() as u32;
    usage
}

/// Combines the messages of a PR's commits. Models and tools are ordered by how many
/// commits credit them (ties keep the order first seen).
pub fn combine<'a>(messages: impl IntoIterator<Item = &'a str>) -> Usage {
    let mut total = Usage::default();
    for m in messages {
        let u = detect(m);
        total.ai_commits += u.ai_commits;
        for c in u.models {
            credit(&mut total.models, &c.name, c.commits);
        }
        for c in u.tools {
            credit(&mut total.tools, &c.name, c.commits);
        }
    }
    total.models.sort_by(|a, b| b.commits.cmp(&a.commits));
    total.tools.sort_by(|a, b| b.commits.cmp(&a.commits));
    total
}

fn credit(list: &mut Vec<Credit>, name: &str, commits: u32) {
    match list.iter_mut().find(|c| c.name.eq_ignore_ascii_case(name)) {
        Some(c) => c.commits += commits,
        None => list.push(Credit {
            name: name.to_string(),
            commits,
        }),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn names(c: &[Credit]) -> Vec<&str> {
        c.iter().map(|c| c.name.as_str()).collect()
    }

    #[test]
    fn claude_code_footer() {
        let u = detect(
            "Fix thing\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\n\n\
             Co-Authored-By: Claude Sonnet 5.5 <noreply@anthropic.com>",
        );
        assert_eq!(names(&u.models), vec!["Claude Sonnet 5.5"]);
        assert_eq!(names(&u.tools), vec!["Claude Code"]);
        assert_eq!(u.ai_commits, 1);
    }

    #[test]
    fn ignores_humans_and_generators() {
        let u = detect("Co-authored-by: Jane Doe <jane@example.com>\nGenerated by protoc");
        assert!(u.is_empty());
        assert_eq!(u.ai_commits, 0);
    }

    #[test]
    fn matches_on_email_and_other_vendors() {
        let u = detect(
            "Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>\n\
             Co-authored-by: bot <x@openai.com>",
        );
        assert_eq!(names(&u.models), vec!["Copilot", "bot"]);
    }

    #[test]
    fn combine_orders_by_commit_count() {
        let opus = "Co-authored-by: Claude Opus 5.5 <noreply@anthropic.com>";
        let sonnet = "Co-Authored-By: claude sonnet 5 <noreply@anthropic.com>";
        let u = combine([
            opus,
            sonnet,
            "plain",
            sonnet,
            "Co-authored-by: CLAUDE OPUS 5.5 <a@anthropic.com>",
        ]);
        // opus: 2 commits, sonnet: 2 commits -> tie keeps first seen (opus)
        assert_eq!(names(&u.models), vec!["Claude Opus 5.5", "claude sonnet 5"]);
        let u = combine([sonnet, sonnet, opus, "plain"]);
        assert_eq!(names(&u.models), vec!["claude sonnet 5", "Claude Opus 5.5"]);
        assert_eq!(u.models[0].commits, 2);
        assert_eq!(u.ai_commits, 3);
    }
}
